---
- name: Run PowerShell script from private Git repository on remote Windows server
  hosts: windows_servers
  gather_facts: false
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Retrieve GitHub credentials from HashiCorp Vault
      community.hashivault.hashi_vault_read:
        address: "{{ vault_address }}"
        token: "{{ vault_token }}"
        secret: "{{ vault_secret_path }}"
        key: "{{ vault_key_username }}"
      register: github_username

    - name: Retrieve GitHub token from HashiCorp Vault
      community.hashivault.hashi_vault_read:
        address: "{{ vault_address }}"
        token: "{{ vault_token }}"
        secret: "{{ vault_secret_path }}"
        key: "{{ vault_key_token }}"
      register: github_token

    - name: Clone Git repository with HTTPS and credentials
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_clone_path }}"
        version: main

    - name: Copy PowerShell script to target machine
      win_copy:
        src: "{{ powershell_script_path }}"
        dest: "{{ temp_dir }}\\tomcat.ps1"

    - name: Execute PowerShell script
      win_shell: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        "{{ temp_dir }}\\tomcat.ps1"
      become_user: Administrator
