---
- name: Install Tomcat on Windows
  hosts: your_windows_group  # Replace with the name of your inventory group containing AWS Windows servers
  gather_facts: false
  become: yes

  tasks:
    - name: Clone Git repository
      git:
        repo: https://github.com/movvamanoj/your-repo.git  # Replace with your Git repository URL
        dest: C:\temp\  # Change the destination directory as needed

    - name: Copy PowerShell script to target machine
      win_copy:
        src: C:\temp\install_tomcat.ps1  # Replace with the path to your PowerShell script in the repository
        dest: C:\install_tomcat.ps1

    - name: Execute PowerShell script
      win_shell: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        C:\install_tomcat.ps1
      become_user: Administrator
